version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
        - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
        - ./wp:/var/www/html # Full wordpress project
        #- ./<plugin-name>/trunk/:/var/www/html/wp-content/plugins/<plugin-name> # Plugin development
        #- ./<theme-name>/trunk/:/var/www/html/wp-content/themes/<theme-name> # Theme development
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

volumes:
  wordpress:
  db: